name: Nix Check (alejandra, deadnix, flake, statix)

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  nix-lints:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v30
        with:
          install_url: https://nixos.org/nix/install
          extra_nix_config: |
            auto-optimise-store = true
            experimental-features = nix-command flakes

      - name: Run Alejandra Check
        run: nix run nixpkgs#alejandra -- --check .

      - name: Run Deadnix Check
        run: nix run nixpkgs#deadnix -- --fail .

      - name: Run Flake Check
        run: nix flake check

      - name: Run Statix Check
        run: nix run nixpkgs#statix -- check .
